'use client'

import { useState, useTransition } from 'react'
import { useRouter } from 'next/navigation'
import { assignOperatorToRequirement, type AssignmentFailureReason } from '@/app/actions/assignment'
import type { AvailableOperator } from '@/lib/repositories/operations'

const messages:Record<AssignmentFailureReason,string>={capacity:'The operator does not have enough vehicle capacity.',conflict:'The operator already has an overlapping trip.',not_found:'The requirement or approved operator was not found.',unauthorized:'You do not have permission to assign operators.',already_assigned:'This requirement has already been assigned.',invalid_schedule:'The requirement has an invalid or incomplete pickup window.',failed:'Assignment failed. No changes were saved.'}
export function AssignmentControl({requirementId,operators}:{requirementId:string;operators:AvailableOperator[]}) { const [operatorId,setOperatorId]=useState(''); const [message,setMessage]=useState<string|null>(null); const [success,setSuccess]=useState(false); const [pending,startTransition]=useTransition(); const router=useRouter(); const assign=()=>startTransition(async()=>{ setMessage(null); const result=await assignOperatorToRequirement(requirementId,operatorId); if(result.ok){setSuccess(true);setMessage('Operator assigned successfully.');router.refresh()}else setMessage(messages[result.reason]) }); return <div className="assignment-control">{success?<span className="assignment-message success">{message}</span>:<><select aria-label={`Operator for ${requirementId}`} value={operatorId} onChange={e=>setOperatorId(e.target.value)} disabled={pending}><option value="">Select operator</option>{operators.map(o=><option key={o.id} value={o.id}>{o.companyName??o.name??o.id} · {o.capacity??'unknown'} seats</option>)}</select><button className="button primary" type="button" disabled={!operatorId||pending} onClick={assign}>{pending?'Assigning…':'Assign'}</button>{message&&<span className="assignment-message danger" role="alert">{message}</span>}</>}</div> }
